"""add Department

Revision ID: 766a4f9472af
Revises: 89da99561323
Create Date: 2025-06-19 19:55:47.190545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766a4f9472af'
down_revision = '89da99561323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
